### ISSUE TITLE
in simulation screen show error when the response from the server is null.

### ISSUE THREAD

**Issue by rohitgeddam** [frg-fossee/eSim-Cloud#125]

**Comment by dssudake** [comment]
Fixed this issue. Pushed latest changes on esim-frontend
ref: [d5e8cc2](https://github.com/frg-fossee/eSim-Cloud/commit/d5e8cc2ff30cf54af5be46a9ce05b55d6dc18529) , [b48fb06](https://github.com/frg-fossee/eSim-Cloud/commit/b48fb06e1bab57576e97fa672db60c4483c7359b)
