### ISSUE TITLE
Failing linting test eSim Cloud

### ISSUE THREAD

**Issue by darshkpatel** [frg-fossee/eSim-Cloud#147]
Ref: https://github.com/frg-fossee/eSim-Cloud/commit/1bbe1c47cb9eb2f5113d64b88ebece8e9575858b#annotation_266692795

**Comment by darshkpatel** [comment]
@felixfaisal Your latest commit seems to break the linting tests

**Comment by felixfaisal** [comment]
Fixed linting issues in the most recent commit
