### ISSUE TITLE
Replacing alert boxes

### ISSUE THREAD

**Issue by NavonilDas** [frg-fossee/eSim-Cloud#148]
In Arduino on Cloud, we use alert boxes. Alert boxes are used for things like Sucess/Fail Message. We need to replace these alert messages with modals. As browser can block multiple alerts messages as well as it decreases UX.

**Comment by gupta-arpit** [comment]
can we close this issue now @firuza ?

**Comment by fresearchgroup** [comment]
Issue resolved by @gupta-arpit
