### ISSUE TITLE
Adding LCD Support

### ISSUE THREAD

**Issue by VishnuEaswaran** [frg-fossee/eSim-Cloud#168]
The current version have a dummy LCD in place but lacks functionality. Let us built an emulator for the same to make it useful.

Some references:
- The LiquidCrystal Arduino library source: https://github.com/arduino-libraries/LiquidCrystal
- de-facto choice of LCD driver: https://en.wikipedia.org/wiki/Hitachi_HD44780_LCD_controller

The name of the popular LCD module is LCD1602 and internally it houses the Hitachi driver.

![image](https://user-images.githubusercontent.com/3790701/88392018-ec575d80-cdd8-11ea-81c9-44e0cb8d51e2.png)

**Comment by VishnuEaswaran** [comment]
An LCD 2*16 simulator: http://www.dinceraydin.com/djlcdsim/djlcdsim.html

**Comment by VishnuEaswaran** [comment]
![image](https://user-images.githubusercontent.com/3790701/89149139-56aa9380-d579-11ea-9f30-eb750e436fbf.png)
towards the bottom of the page, we have a download option which seems to be of the source code. Said that, there is no license in the download.

**Comment by firuza** [comment]
https://github.com/visrealm/vrEmuLcd

**Comment by firuza** [comment]
Implemented by gupta-arpit. Feature merged in develop branch.
