### ISSUE TITLE
enable component placement on breadboard

### ISSUE THREAD

**Issue by VishnuEaswaran** [frg-fossee/eSim-Cloud#169]
The breadboard though has all the electrical characteristics right, one cannot place a component on it; wires needs to be drawn from each pin/leg to nodes on the board. Wires perfectly work at the moment.

We should be able to place them and have proper connections like the following

![image](https://user-images.githubusercontent.com/3790701/88392455-ab137d80-cdd9-11ea-97d6-445297c2f04b.png)

**Comment by firuza** [comment]
merged by @gupta-arpit in #181
