### ISSUE TITLE
UX: Pressing escape should delete the in-progress connection line

### ISSUE THREAD

**Issue by gupta-arpit** [frg-fossee/eSim-Cloud#171]
- If you're in the process of connecting nodes, pressing `esc` should delete the in-progress line.
Currently, the user has to do a right-click and then click 'Delete'

<img width="733" alt="image" src="https://user-images.githubusercontent.com/12170429/89074233-a6326900-d399-11ea-8668-75cc82a524a2.png">

**Comment by NavonilDas** [comment]
To remove existing wire press **Delete**  Key.

If you want to change the key to **ESC** Update the following Line in [Workspace.ts](https://github.com/frg-fossee/eSim-Cloud/blob/master/ArduinoFrontend/src/app/Libs/Workspace.ts#L423).

**Comment by gupta-arpit** [comment]
I am using macOS, I tried pressing the delete button. It doesn't work

**Comment by NavonilDas** [comment]
> I am using macOS, I tried pressing the delete button. It doesn't work

Not Sure about mac but it works perfectly on windows.

**Comment by firuza** [comment]
Implemented by @gupta-arpit in #178
