### ISSUE TITLE
Components and breadboard issue

### ISSUE THREAD

**Issue by firuza** [frg-fossee/eSim-Cloud#188]
Components dropped on certain part of the breadboard do not simulate as expected. However, if connected using wires they work fine. Tested with LED, Buzzer, and RGB LED.

![LED_Breadboard_issue](https://user-images.githubusercontent.com/7722581/92584567-6d978080-f2b1-11ea-9b6e-7e782832a9f5.GIF)

![LED_Breadboard_issue2](https://user-images.githubusercontent.com/7722581/92584589-75efbb80-f2b1-11ea-9bb5-42acc152449c.gif)

**Comment by gupta-arpit** [comment]
Raised #190 to fix the issue.

Regards,
Arpit

**Comment by firuza** [comment]
Fixed by Arpit in #190
