### ISSUE TITLE
Pressing Backspace on some textfield triggers delete component functionality

### ISSUE THREAD

**Issue by ikartikgautam** [frg-fossee/eSim-Cloud#237]
**Steps to replicate the issue:**
1. Drag a component from the left side into schematic
2. Click on any text field on the website
3. Hit backspace in textfield
4. The component dragged gets deleted if it's selected, if it's not selected then a banner shows up indicating "No element is selected".

**Expected Behaviour**
When a user is typing in a textfield, Instead of deleting the component, it should just delete the text in the textfield.

**OS tested on**: Ubuntu(Linux)

**Comment by firuza** [comment]
Fixed and merged in #241
