### ISSUE TITLE
Netlist corresponding to equivalent circuits differ in case of supernodes when the points of connections are altered in eSim

### ISSUE THREAD

**Issue by Kaustuv942** [frg-fossee/eSim-Cloud#243]
In a situation where multiple points are connected through a supernode involving (say) three components C1, R1, and Q1, it was observed when the connection of the three components was made at the R1 node resulted in a different netlist than when the same connection was made at C1 node. 

In effect, both the circuits are equivalent and should result in the same graph. This is a case of an error in the generation of the netlist.
![Supernodebug (3)](https://user-images.githubusercontent.com/56028031/118972324-0ed0ed80-b98e-11eb-8401-cfdb53cbd55c.gif)

**Comment by felixfaisal** [comment]
Hey, @Kaustuv942 there's an option to view the netlist, So if you could check the netlist before and after you made the change then you can better analyze where the problem lies.

**Comment by firuza** [comment]
Fixed in #336
