### ISSUE TITLE
Deleting a wire sometimes deletes other component's wire too on breadboard

### ISSUE THREAD

**Issue by ikartikgautam** [frg-fossee/eSim-Cloud#300]
**Description:** In some circuits when we delete any wire, then other component's wire too get deleted

**TESTED ON CIRCUIT:**
<img width="941" alt="Screenshot 2021-07-01 at 8 28 10 AM" src="https://user-images.githubusercontent.com/39825660/124058708-855e1200-da47-11eb-9687-3e08022e3fde.png">

**WIRE DELETED:**
<img width="941" alt="Screenshot 2021-07-01 at 8 28 10 AM" src="https://user-images.githubusercontent.com/39825660/124058806-b2aac000-da47-11eb-9824-e059e174674d.png">

**EFFECT ON LED's WIRE:**
<img width="836" alt="Screenshot 2021-07-01 at 8 26 59 AM" src="https://user-images.githubusercontent.com/39825660/124058912-e1c13180-da47-11eb-8d96-7050bb5e7e5e.png">

**REASON:**
I did a bit of debugging and encountered an issue, which I think is the reason for it. 
Actually when the circuit is being created then two wires get the same `id`. Due to this reason when one wire with same `id` is deleted then another wire too gets deleted partially.(See pictures below)
<img width="818" alt="Screenshot 2021-07-01 at 8 24 49 AM" src="https://user-images.githubusercontent.com/39825660/124059325-893e6400-da48-11eb-96cd-79b80117726f.png">
_In the above image, you can observe that `id` of two wires is same whereas the `end` and `start` nodes are different and has nothing to do with each other._

**Tested on:** Live website & develop branch
**OS:** macOS

**Comment by firuza** [comment]
Fixed in #303
