### ISSUE TITLE
LED can not determine if Negative terminal is connected to arduino GND or not

### ISSUE THREAD

**Issue by ikartikgautam** [frg-fossee/eSim-Cloud#318]
**Brief:** LED component lack a check if it is connected to Arduino's Ground(GND) or not, whilst it is connected using a breadboard. This results in running of LED even when only positive terminal is connected to arduino.

**Project:** Arduino on Cloud

**Steps to Reproduce:** 
1. Create any basic structure with Arduino, LED & breadboard in which LED glows.
2. Delete the wires connected to the 'Negative' terminal.
3. Run the simulation.
4. LED will still glow. (see image below)
<img width="1006" alt="LED still glowing" src="https://user-images.githubusercontent.com/39825660/125196789-bbd23300-e278-11eb-87c1-c7becda781d4.png">

**Expected Behaviour:**
LED should not glow & prompt the user if the wire is not connected.

**Tested on:** Develop branch

**OS Used:** macOS 11

**Comment by firuza** [comment]
Fixed in #319
