### ISSUE TITLE
Breadboard does not work as expected in case of deeply nested circuits

### ISSUE THREAD

**Issue by ikartikgautam** [frg-fossee/eSim-Cloud#324]
**Brief:** A few circuits do not change the value of same line oriented nodes in breadboard. This happens in deeply nested circuits which need value to be transferred from one wire to another and then on another node of breadboard.

**Steps to Reproduce:**
1. Implement a similar circuit as given below in this Image.
2. Click on start simulation.
3. LED won't glow.
<img width="881" alt="Screenshot 2021-07-13 at 9 22 06 PM" src="https://user-images.githubusercontent.com/39825660/125487561-6a9e0c6f-830d-4e6e-9dfb-72ecfbd67bc5.png">

**Expected Behaviour:** LED must glow.

**REASON for problem:**
<img width="570" alt="Screenshot 2021-07-13 at 10 16 18 PM" src="https://user-images.githubusercontent.com/39825660/125493164-cacdf7c3-ca0d-4a93-888c-4aee1c5c516c.png">
In above image the nodes that are marked in **blue** rectangle are not able to set value for whole set of nodes, received from nodes marked with 2 and 1.

**Tested on:** Live website & develop branch

**Browser:** Chrome 91 (macOs)

**Comment by firuza** [comment]
Fixed in #325
