### ISSUE TITLE
Failing Build eda-frontend

### ISSUE THREAD

**Issue by darshkpatel** [frg-fossee/eSim-Cloud#46]
Build is failing due to linting issues in files 
./src/components/SchematicEditor/Helper/ComponentDrag.js
./src/components/SchematicEditor/Helper/SideBar.js

**Comment by darshkpatel** [comment]
@felixfaisal

**Comment by darshkpatel** [comment]
./src/components/SchematicEditor/Helper/xml_parser.js is also throwing linting errors @rohitgeddam

**Comment by darshkpatel** [comment]
In the latest run , the tests are failing due to the hardcoded svg imports, 
https://github.com/frg-fossee/eSim-Cloud/runs/684106962

**Comment by darshkpatel** [comment]
```

      1 | import mxGraphFactory from "mxgraph";
    > 2 | import comp1 from "../../../static/CircuitComp/U-4001-1:A.svg";
        | ^
```
``` src/components/SchematicEditor/Helper/ComponentDrag.js:2:1 ```

**Comment by dssudake** [comment]
@darshkpatel I have fixed issue. Pushed latest changes on eda-toolbar.
ref: [ddec2d1](https://github.com/frg-fossee/eSim-Cloud/commit/ddec2d197423fbbd0fc90ea6a2e0e22314ec529f)
https://github.com/frg-fossee/eSim-Cloud/runs/684448462
