### ISSUE TITLE
Moving the push button after simulation

### ISSUE THREAD

**Issue by nagsides** [frg-fossee/eSim-Cloud#465]
Place an Arduino, a breadboard, and a push button switch on the breadboard as shown int he screenshot below. Now, simulate once and stop the simulation. In this case, the push button cannot be moved to a different location on the breadboard. There is a potential bug in the way the movement of the push button is handled.
![image](https://user-images.githubusercontent.com/7682775/218028888-d2972195-bb86-43ab-bceb-d749c126883f.png)

**Comment by RAKSHIT-RAJ2028** [comment]
Assignee: @RAKSHIT-RAJ2028

**Comment by firuza** [comment]
@RAKSHIT-RAJ2028 : This has been handled.

**Comment by firuza** [comment]
fixed pushed in the develop

**Comment by RAKSHIT-RAJ2028** [comment]
assign any new task in Arduino on cloud
