### ISSUE TITLE
LED not glowing/blinking when connected to Resistor and Arduino 

### ISSUE THREAD

**Issue by rinon13** [frg-fossee/eSim-Cloud#469]
Description: LED is not glowing when either pins (POSITIVE or NEGATIVE) is connected to Arduino's Digital Pins with a resistor in between.

Steps to Reproduce:

![LED_Resistor_AllDigitalPins](https://user-images.githubusercontent.com/87307364/219583019-58a1c30d-333b-499c-bfdc-cc286eecc4cc.png)

1. Implement similar circuit as shown.
2. Copy .ino code 

```int  POS_PIN = 13;
int NEG_PIN = 12;

void setup(){
    pinMode(POS_PIN, OUTPUT);
    pinMode(NEG_PIN, OUTPUT);
    digitalWrite(NEG_PIN, LOW);
}

void loop(){
    digitalWrite(POS_PIN, HIGH);
    delay(500);
    digitalWrite(POS_PIN, LOW);
    delay(500);
}
```

3. Press "Start Simulation"
4. LED won't blink as expected in .ino code.

Expected behavior: LED should blink.

Reason for the problem: When a resistor is connected between the LED's pins and the Arduino's digital pins, the LED is unable to fetch the value of the digital pins.

 - OS: Ubuntu 22.04.1 LTS
 
Browser: Firefox 110 (Ubuntu)

Tested on:
- simulation.iitbx.in
- develop 
- https://github.com/rinon13/eSim-Cloud/tree/LED_Pin_Connection_Issue (Fixed issue where both NEGATIVE and POSITIVE pins of LED are not working when connected to Digital Pins of Arduino)

Additional Context:
1. LED will work as intended (blink in intervals) when NEGATIVE pin is connected to GND instead of a digitally programmed LOW Arduino Pin ( digitalWrite(NEG_PIN, LOW); ).

![LED_Blink_Issue2](https://user-images.githubusercontent.com/87307364/219600689-87ac3abe-59c4-4531-9a9c-464c963fc682.gif)

**Comment by firuza** [comment]
Fixed in #467
