### ISSUE TITLE
Servo not detecting Arduino after reconnection

### ISSUE THREAD

**Issue by rinon13** [frg-fossee/eSim-Cloud#472]
Description: Signal pin of Servo not able to detect/get value from Arduino's pin after deleting and connecting to it again. Error message "Arduino not found" is shown.

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/87307364/220171567-1bce971c-a648-4f36-b30f-777dd026d600.png)

1. Connect as shown above or get the circuit directly from Gallery (name of circuit is Servo)
2. Add .ino code 

```
#include <Servo.h>
Servo myservo;
int pos = 0;

void setup() {
   myservo.attach(3);
}

void loop() {
    for (pos = 0; pos <= 180; pos += 1) {
      myservo.write(pos);
      delay(15);
    }
    for (pos = 180; pos >= 0; pos -= 1) {
        myservo.write(pos);
        delay(15);
    }
}
```

3. Press "Start Simulation" (Servo will start to rotate)
4. Press "Stop Simulation"
5. Remove/delete wire connecting from connected Arduino pin (pin 3 in above photo) to Signal pin of Servo
6. Connect a wire from programmed Arduino pin (pin 3) to Signal pin of Servo again
7. Press "Start Simulation" 
9. Error message "Arduino not found" will be shown and Servo will not work

Video of entire process:

[Servo_Double_Connection_Issue.webm](https://user-images.githubusercontent.com/87307364/220173062-ab0afe83-746c-4376-9c1f-71605bca47d3.webm)

Expected behavior: Servo should work after connecting back to programmed pin of Arduino (pin 3 in our case)

 - OS: Ubuntu 22.04.1 LTS
 - Browser: Firefox 110

Tested on:
- develop
- simulation.iitbx.in

**Comment by firuza** [comment]
Fixed in #477
