### ISSUE TITLE
Servo connection issue

### ISSUE THREAD

**Issue by rinon13** [frg-fossee/eSim-Cloud#474]
Description: Servo working when it's POWER and GND pins are connected wrongly.

Pins of Servo:

![Servo_GND](https://user-images.githubusercontent.com/87307364/220180503-f26c6ac2-e9bd-48d9-a21b-628b71f6950b.png)
GND pin

![Servo_Power](https://user-images.githubusercontent.com/87307364/220180506-8b14bcab-a6f3-41f4-a467-2bf83c3bbd2e.png)
POWER pin

![Servo_Signal](https://user-images.githubusercontent.com/87307364/220180557-c8a63e04-b69e-404d-83ce-c9172cd7a878.png)
Signal Pin

Scenario 1:  GND connected to unprogrammed Arduino pin
![Servo_GND_Unprogrammed_Pin](https://user-images.githubusercontent.com/87307364/220181414-6171ae3c-a41c-4946-a550-3aa5bfa136d9.png)

Scenario 2: GND connected to disconnected Resistor
![Servo_Gnd_Uncon_Resistor](https://user-images.githubusercontent.com/87307364/220181441-97e63f94-4f76-48bf-9cda-8d14b3472105.png)

Scenario 3:  POWER connected to unprogrammed Arduino pin
![Servo_Power_Unprog_Pin](https://user-images.githubusercontent.com/87307364/220181473-02997cd2-d35b-4c35-98f9-af108b77cee0.png)

Scenario 4 : POWER and GND connected to each other
![Servo_GND_Power](https://user-images.githubusercontent.com/87307364/220181543-1e2349ba-f3f2-4c7d-80b9-a6d80b88e26e.png)

Scenario 5: POWER connected to GND of Arduino and GND connected to 5v of Arduino
![image](https://user-images.githubusercontent.com/87307364/220182061-ae86950f-b8a7-41c6-9bce-e0f347dbd349.png)

Steps to Reproduce:

1. Connect as shown in Scenarios shown above
2. Copy .ino code 
```
#include <Servo.h>
Servo myservo;
int pos = 0;

void setup() {
   myservo.attach(3);
}

void loop() {
    for (pos = 0; pos <= 180; pos += 1) {
      myservo.write(pos);
      delay(15);
    }
    for (pos = 180; pos >= 0; pos -= 1) {
        myservo.write(pos);
        delay(15);
    }
}


```
3. Press "Start Simulation"
4. Servo will work

Expected Behavior: Servo should not work in any of the Scenarios above.

Version and OS:
 - OS: Ubuntu 22.04.1 LTS 
 - Browser: Firefox 110

Tested on
 - develop
 - simulation.iitbx.in

Additional Context

- POWER and GND can also be connected to other components such as unconnected pin of BreadBoard and it will still work
![image](https://user-images.githubusercontent.com/87307364/220181200-6b907446-2a3d-4ee2-9168-5bd7226af4bd.png)

**Comment by firuza** [comment]
Fixed in #477
