### ISSUE TITLE
Unable to execute different .ino codes for different Arduinos

### ISSUE THREAD

**Issue by rinon13** [frg-fossee/eSim-Cloud#478]
Description: When two different .ino codes are copied to two different Arduinos, the 1st Arduino's .ino code is overwritten by the 2nd one.

Steps to Reproduce

![image](https://user-images.githubusercontent.com/87307364/220904565-27fbe099-3359-419e-b8be-11f76fdcf9f5.png)

1. Connect as shown above or take circuit from Gallery (Two Arduinos)
2. Copy .ino code to first Arduino
```
void setup(){
	pinMode(13, OUTPUT);
}

void loop(){
	digitalWrite(13, HIGH);
    delay(1000);
	digitalWrite(13, LOW);
    delay(1000);
}
```
3. Copy .ino code to second Arduino
```
void setup(){
	pinMode(12, OUTPUT);
    digitalWrite(12, HIGH);
}

void loop(){
}
```
4. Check the .ino code of the first Arduino
5. The .ino code of the first Arduino would have been overwritten by the second one
6. If a different .ino code is copied/written to the first Arduino, the second one's code would also get overwritten

Expected Behavior: The .ino code of the respective Arduinos should not affect the other Ardionos. Different n number of .ino codes should be able to be written for n number of Arduinos.

Video of the process mentioned above:
[Arduino_Parallel_Execution_Issue.webm](https://user-images.githubusercontent.com/87307364/220991500-691f5193-d18d-4044-a97f-0e37f45009b3.webm)

Additional information: The LED of Arduino 2 blinking even though the code does not provide any LOW input is a bug. (Already mentioned in Issue #476 ).

Version and OS:
 - OS: Ubuntu 22.04.1 LTS 
 - Browser: Firefox 110

Tested on:
 - develop
 - simulation.iitbx.in

**Comment by firuza** [comment]
Fixed in #479
