### ISSUE TITLE
RGB LED Cathode pin issue

### ISSUE THREAD

**Issue by rinon13** [frg-fossee/eSim-Cloud#480]
Description: The Cathode pin of RGB LED should only be connected to the GND pin or a digitally programmed 0 pin for RGB LED to work. In scenarios mentioned below, it is working when connected to any pin.

![image](https://user-images.githubusercontent.com/87307364/221411970-d5a92286-8038-46e3-a11a-92f1bada5e40.png)
Cathode pin

Scenarios:

![RGB_LED_Unconnected_Resistor](https://user-images.githubusercontent.com/87307364/221411878-3ae1d1aa-3fe9-460b-8a75-ffc9165fa6f2.png)
Cathode pin connected to an unconnected resistor

![RGB_LED_5V](https://user-images.githubusercontent.com/87307364/221411901-1a9be88b-7fb8-498a-aa7f-e4f515e0ec91.png)
Cathode pin connected to a 5V pin

Steps to Reproduce

1. Connect as shown above
2. Copy .ino code
```
void setup(){
	pinMode(11, OUTPUT);
	pinMode(9, OUTPUT);
	pinMode(7, OUTPUT);
}

void loop(){
	for(int i=1;i<=7;++i){
        digitalWrite(11, i&1);
        digitalWrite(9, (i>>1)&1);
        digitalWrite(7, (i>>2)&1);
        delay(1000);
    }
}
```
3. Press "Start Simulation"
4. RGB LED will work

Expected Behavior:Should only work when Cathode pin is connected to GND or digitally programmed LOW (0) pin.

[RGB LED.webm](https://user-images.githubusercontent.com/87307364/221412094-7f70374b-58cb-464d-8e8a-ab523b553c5c.webm)
Video of above scenarios

Version and OS:
 - OS: Ubuntu 22.04.1 LTS 
 - Browser: Firefox 110

Tested on
 - develop
 - simulation.iitbx.in

**Comment by firuza** [comment]
fixed in #481
