### ISSUE TITLE
arduino path improperly configured

### ISSUE THREAD

**Issue by darshkpatel** [frg-fossee/eSim-Cloud#78]
```http://localhost/arduino/```
Base href environment variable does not seem to affect the development build paths and still tries to load assets from ``` / ```

<img width="369" alt="Screenshot 2020-05-27 at 10 41 17 AM" src="https://user-images.githubusercontent.com/11258286/82980296-be3ae480-a006-11ea-84fe-692a8ea62342.png">

**Comment by darshkpatel** [comment]
same thing happens for the production config , built js files are fine , but the paths are not affected by changing the base href 
```http://localhost/assets/images/arduino.JPG```
it should be loading images from ``` http://localhost/arduino/assets/images/arduino.JPG```
must be a setting in angular build 
@NavonilDas  can you have a look

**Comment by NavonilDas** [comment]
@darshkpatel The Base Href should work.
In the build config, we only need to mention the assets directory it basically copies the assets directory to build directory.

I guess we can do one thing add a /assets route in NGINX Config. It will also help us cache images & js files.

**Comment by darshkpatel** [comment]
All images are already being cached globally so don't have to define a different route for it. 

Updating the angular config and changing the base url properly might be a better approach than reserving the assets route. 

For react it's simply setting the host url checkout the env file

**Comment by NavonilDas** [comment]
@darshkpatel the build configs are correct. I guess on **"../assets"** needs to be updated as **"./assets"** on the dashboard. Can you open the simulator **localhost/arduino/simulator** and see if the images on components are loading properly.

**Comment by darshkpatel** [comment]
> @darshkpatel the build configs are correct. I guess **"../assets"** needs to be updated as **"./assets"** on the dashboard. Can you open the simulator **localhost/arduino/simulator** and see if the images on components are loading properly.

![Screenshot 2020-05-27 at 12 58 12 PM](https://user-images.githubusercontent.com/11258286/82990426-cd775d80-a019-11ea-91e7-fcb50b4e1d71.png)

**Comment by darshkpatel** [comment]
https://github.com/frg-fossee/eSim-Cloud/blob/966db7d0d8ac448d97f99e2199e41a009d47ecee/Nginx/conf.d/local.conf#L62

That snipped does not seem to be able to fix the issue , i cant seem to figure it out. Any ideas ?

**Comment by darshkpatel** [comment]
<img width="665" alt="Screenshot 2020-05-30 at 12 08 15 PM" src="https://user-images.githubusercontent.com/11258286/83321593-54247880-a26e-11ea-91ee-679a56abcea1.png">

@NavonilDas It's still loading stuff from /assets
